config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { registrations: "registrations"}
  resources :portfolios, :comments
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root 'welcome#index'
  get '/admin', to: 'admin#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :portfolio
  validates :body, length: {:minimum => 5, maximum: 3000}
end

app/models/portfolio.rb
class Portfolio < ApplicationRecord
  has_many :comments, dependent: :delete_all
  mount_uploader :picture, PortfolioPictureUploader
  mount_uploader :icon, PortfolioIconUploader
  validates :link_name, :link_href, presence: true, unless: :link_empty?

  def date
    "#{month}/#{year}"
  end

  private
  def link_empty?
    link_name.empty? && link_href.empty?
  end

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable, :recoverable, :rememberable, :validatable
end

app/controllers/admin_controller.rb
class AdminController < ApplicationController
  before_action :authenticate_user!

  def index
    redirect_to root_path
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  def create
    @comment = Comment.new(comments_params)
    portfolio = Portfolio.find params[:comment][:portfolio_id]
    if @comment.save
      redirect_to portfolio
    else
      flash[:warning] = 'Please enter at least 5 symbols.' if @comment.body.length < 5
      flash[:warning] = 'Please enter not more than 3000 symbols.' if @comment.body.length > 3000
      redirect_to portfolio
    end
  end

  private

  def comments_params
    params.require(:comment).permit(:body, :portfolio_id)
  end
end

app/controllers/portfolios_controller.rb
class PortfoliosController < ApplicationController
  before_action :authenticate_user!, except: [:show, :index]
  before_action :set_portfolio, only: [:show, :destroy, :edit, :update]

  def index
    redirect_to root_path
  end

  def show
    @comment = Comment.new portfolio_id: @portfolio.id
  end

  def edit
  end

  def update
    if @portfolio.update portfolio_params
      flash[:success] = "Portfolio updated successfully!"
      redirect_to @portfolio
    else
      flash.now[:error] = "Item not saved. Please check your input."
      render 'edit'
    end
  end

  def destroy
    if @portfolio.destroy
      flash[:notice] = 'Portfolio item removed successfully.'
      redirect_to root_path
    else
      flash[:error] = 'Portfolio item could not be removed.'
      redirect_to root_path
    end
  end

  def new
    @portfolio = Portfolio.new
  end


  def create
    @portfolio = Portfolio.new(portfolio_params)

    if @portfolio.save
      redirect_to @portfolio
    else
      render 'new'
    end
  end

  private

  def set_portfolio
    @portfolio = Portfolio.find params[:id]
  end
end

private

def portfolio_params
  params.require(:portfolio).permit(:title, :body, :picture, :icon, :likes, :year, :month, :link_href, :link_name)
end

app/controllers/registrations_controller.rb
class RegistrationsController < Devise::RegistrationsController
  before_action :one_user_registered?, only: [:new, :create]

  protected

  def one_user_registered?
    if User.count == 1
      if user_signed_in?
        redirect_to root_path
      else
        redirect_to new_user_session_path
      end
    end
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
    page = params[:page]
    if user_signed_in?
      per = 5
    else
      per = 6
    end
    @portfolio_list = Portfolio.order('year DESC, month DESC').page(page).per(per)
    @comments = Comment.order('created_at').limit(10).reverse
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def r_flash
    output = ''
    flash.each do |type, message|
      next if message.blank?

      type = :success if type.to_sym == :notice
      type = :error if type.to_sym == :alert
      next unless SemanticFlashHelper::ALERT_TYPES.include?(type.to_sym)

      output += r_flash_container(type, message)
    end

    raw(output)
  end

  def r_flash_container(type, message)
    render(partial: 'layouts/toast', locals: {message: message, type: type})
  end
end

app/views/comments/_feed.html.erb
<div class="ui feed">
  <% comments.each do |comment| %>
    <div class="event">
      <div class="label">
      </div>
      <div class="content">
        <div class="summary">
          <span style="color: orange;">Someone</span> commented
          <div class="date">
            <%= time_ago_in_words comment.created_at %>
          </div>
        </div>
        <div class="extra text">
          <%= comment.body %>
        </div>
      </div>
    </div>
  <% end %>
  <%= form_for @comment do |f| %>
    <div class="ui action input fluid">
      <%= f.text_field :body, placeholder: "Enter your comment", type: 'text' %>
      <%= f.button ("Send" + icon('far', 'paper-plane', style: 'padding-left: 0.5rem;')).html_safe, class: 'ui button orange' %>
      <%= f.hidden_field :portfolio_id %>
    </div>
  <% end %>
</div>

app/views/comments/_last_comments.html.erb
<% @comments.each do |comment| %>
  <div class="event">
    <div class="content">
      <div class="summary">
        <%= "#{time_ago_in_words(comment.created_at)}: #{comment.body}" %>
      </div>
    </div>
  </div>
<% end %>

app/views/layouts/_footer.html.erb
<footer style="padding-bottom: 10em;" class="bottom aligned container">

</footer>

app/views/layouts/_navbar.html.erb
<div class="ui top fixed menu">
  <div>
    <a class="item header" href="<%= root_path %>"><%= image_tag 'R.png', style: 'margin-right: 0.5em;' %>
      My Portfolio
    </a>
  </div>
  <a href="https://rubeen.one" class="item">Visit my website</a>
  <% if user_signed_in? %>
    <div class="right menu">
      <%= link_to 'Logout', destroy_user_session_path, class: 'item active red', method: :delete %>
    </div>
  <% end %>
</div>

app/views/layouts/_toast.html.erb
<script>
    $('main').toast(
        {
            class: '<%= type %>',
            message: '<%= message %>'
        });
</script>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>RPortfolio</title>
  <%= csrf_meta_tags %>
  <%= csp_meta_tag %>
  <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0">
  <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
</head>

<body>
<%= render 'layouts/navbar' %>
<main class="ui container">
  <%= yield %>
</main>
<%= render 'layouts/footer' %>
<%= r_flash %>
</body>
</html>

app/views/portfolios/_admin_item.html.erb
<div class="ui raised card">
  <div class="extra content">
    Admin Panel
  </div>
  <div class="content">
    <%= link_to 'Create new Portfolio item', new_portfolio_path, class: 'ui fluid positive button' %>
  </div>
  <% unless @comments.empty? %>
    <div class="extra content">
      <h3>Last comments</h3>
      <%= render 'comments/last_comments' %>
    </div>
  <% end %>
</div>

app/views/portfolios/_form.html.erb
<%= form_for @portfolio, html: {multipart: true} do |f| %>
  <div class="ui form">
    <div class="two fields">
      <div class="field">
        <%= f.label :title %>
        <%= f.text_field :title, placeholder: 'Title' %>
      </div>
      <div class="field two fields">
        <div class="field">
          <%= f.label :year %>
          <%= f.number_field :year, placeholder: 'Year' %>
        </div>
        <div class="field">
          <%= f.label :month %>
          <%= f.number_field :month, placeholder: 'Month' %>
        </div>
      </div>
    </div>
    <div class="field">
      <%= f.label :body, 'Content' %>
      <%= f.text_area :body %>
    </div>
    <div class="two fields">
      <div class="field">
        <%= f.label :link_name %>
        <%= f.text_field :link_name, placeholder: 'Link name' %>
      </div>
      <div class="field">
        <%= f.label :link_href %>
        <%= f.text_field :link_href, placeholder: 'Link href' %>
      </div>
    </div>
    <div class="field">
      <label>Icon image <%= image_tag @portfolio.icon.url, class: 'ui mini spaced image' if @portfolio.icon? %></label>
      <%= f.file_field :icon, accept: 'image/jpeg,image/png', class: 'field' %>
    </div>
    <div class="field">
      <label>Cover image <%= image_tag @portfolio.picture.url, class: 'ui mini spaced image' if @portfolio.picture? %></label>
      <%= f.file_field :picture, accept: 'image/jpeg,image/png', class: 'field' %>
    </div>

    <%= f.submit class: 'ui button positive fluid' %>
  </div>
<% end %>

app/views/portfolios/_item_list.html.erb
<div class="ui three stackable cards">
  <%= render 'portfolios/admin_item' if user_signed_in? %>
  <% @portfolio_list.each do |portfolio| %>
    <%= render 'portfolios/portfolio_item', portfolio: portfolio %>
  <% end %>
</div>

<% unless @portfolio_list.total_pages <= 1 %>
<div style="margin-top: 5em" class="ui">
      <nav class="ui content pagination menu">
        <% if @portfolio_list.prev_page %>
        <%=  link_to_prev_page @portfolio_list, '<div>Previous page </div>'.html_safe, class: 'item text aligned center'  %>
        <%  end  %>
        <%  if @portfolio_list.next_page  %>
        <%=  link_to_next_page @portfolio_list, '<div>Next page</div > '.html_safe, class: 'item text aligned center '  %>
        <%  end  %>
      </nav>
</div>
<%  end %>

app/views/portfolios/_portfolio_item.html.erb
<% if portfolio %>
  <%= link_to portfolio, class: 'ui raised link card' do %>
    <div class="content">
      <div class="right floated meta">
        <%= portfolio.date %>
      </div>
      <h2 class="ui no-link header">
        <%= image_tag portfolio.icon.url, style: 'height: 1em; width: auto;', class: 'ui avatar image' if portfolio.icon? %>
        <div class="content" style="width: 80%;">
          <%= portfolio.title %>
        </div>
      </h2>
    </div>
    <% if portfolio.picture? %>
      <div class="image">
        <%= image_tag portfolio.picture.url if portfolio.picture? %>
      </div>
    <% end %>
    <div class="content no-link">
      <%= portfolio.body.truncate_words(20) %>
    </div>
    <div class="extra content">
      <%= icon('far', 'comment') %>
      <%= portfolio.comments.count %> comments
    </div>
  <% end %>
<% end %>

app/views/portfolios/edit.html.erb
<h1>Edit Portfolio item #<%= @portfolio.id %></h1>

<%= render 'portfolios/form' %>

app/views/portfolios/new.html.erb
<h1>New Portfolio item</h1>

<%= render 'portfolios/form' %>

app/views/portfolios/show.html.erb
<h1 class="ui top attached header">
  <%= image_tag @portfolio.icon.url, height: 30, class: 'ui image' if @portfolio.icon? %>
  <div class="content">
    <%= @portfolio.title %>
  </div>
</h1>

<div class="ui attached segment">
  <%= image_tag @portfolio.picture.url, height: 100, class: 'ui rounded fluid image' if @portfolio.picture? %>
</div>

<div class="ui attached segment">
  <h2 class="header">Some information</h2>
  <%= @portfolio.body %>
  <% if @portfolio.link_href? %>
    <h3>Project-Link</h3>
    <%= link_to @portfolio.link_name, @portfolio.link_href, class: 'ui button primary fluid' if @portfolio.link_href %>
  <% end %>
</div>

<div class="ui <%= 'bottom' unless user_signed_in? %> attached segment">
  <div class="content">
    <h2>Comments</h2>
    <%= render 'comments/feed', comments: @portfolio.comments %>
  </div>
</div>

<% if user_signed_in? %>
  <div class="ui bottom attached header">
    <h2 class="header">Admin panel</h2>
    <%= link_to 'Edit', edit_portfolio_path(@portfolio), method: :get, class: 'ui fluid button orange' %>
    <%= link_to 'Delete', @portfolio, method: :delete, class: 'ui fluid button red' %>
  </div>
<% end %>

app/views/welcome/index.html.erb
<h1 class="ui header">My Portfolio</h1>

<%= render 'portfolios/item_list' %>